version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_MULTIPLE_DATABASES: memes_db,airflow

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    build: .
    image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}

    command: bash /opt/airflow/init-airflow.sh
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER: ${REDDIT_USER}

    volumes:
      - ./init-airflow.sh:/opt/airflow/init-airflow.sh
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
    depends_on:
      postgres:
        condition: service_healthy



  minio:
    image: quay.io/minio/minio
    container_name: minio
    
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
    - ./minio/data:/data
    
    command: server /data --console-address ":9001"

  dashboard:
    build: dashboard/.
    ports:
      - "8501:8501"
    depends_on:
      - postgres
        
    extra_hosts:
      - "host.docker.internal:host-gateway"



volumes:
  postgres-db-volume:

